### PR TITLE
Add C# version of TiltBrushToolkit

### PR DESCRIPTION
**Pull request by Prystopia**
Direct copy of python tools in C# covering parsing and writing .tilt files and parsing .json Tilt Brush export files.

### CODE REVIEW

**Comment by Prystopia** [comment]
I signed it

**Comment by dubois** [comment]
Hi. Thank you for the contribution! Unfortunately, we don't have the staffing to code-review and support new 3rd party code. Please consider forking instead.

**Comment by andybak** [comment]
Actually - this would probably be better placed in a separate repo.

(However - note to the dev team. This isn't giving out a terribly positive signal about the future of this project - activity across Google VR has been pretty quiet for months. Is it time to move on?)

**Comment by Prystopia** [comment]
Hi, I understand, it was a big piece of work to be checked through, thank you for your time.

I have uploaded the project into a new repo, which can be found [here](https://github.com/Prystopia/c-sharp-tiltbrush-toolkit)

**Comment by Prystopia** [comment]
Yeah, the project was created for use within my Masters thesis, which did exactly that, using evolutionary algorithms to create and amend Tilt Brush models, you can create some really cool pieces of art.

**Comment by n1ckfg** [comment]
That sounds amazing--have you posted the results anywhere?

**Comment by Prystopia** [comment]
Thank you, no not yet, I am hoping to get something set up within the next week, but I'll reply to this thread as soon as it's live.

**Comment by dubois** [comment]
Regarding algorithmic modification of Tilt Brush sketches, we just released
an Artist in Residence project called A Show of Kindness on Steam.

It uses a technique where the tilt is exported to USD (which the lastest TB
supports now). USD is a Pixar format gaining traction in the 3d industry,
and it has robust scripting and tooling support. The USD we export contains
all the information from the .tilt as well as the fbx.

Jeremy Cowles (who was also the designer of USD) manipulated the USD scene
to modify stroke timings and such, then imported it back into a new Unity
project using USD.NET, which he wrote and made available on GitHub.

Personally, I think this approach is the correct one; rather than try to
add another  file format into the ecosystem, Tilt Brush should export to
existing formats. It's just that before USD, there was no good candidate.

Looking forward to hearing more about your project!

>

**Comment by n1ckfg** [comment]
Wow, I had no idea that USD could support a displaying sequence of brushstrokes in a standardized way. (I've used hide or scale keyframes for exchange before, but I find those aren't interpreted consistently across different apps.) That said, I do find tilt files are an efficient way to preserve 
 the original stroke information--I've got tilt import support in my Blender Grease Pencil plugin ( https://github.com/LightningArtist/latk_blender ), but no export because all the code examples I've seen assume you're modifying an existing tilt file. (I've tried some permutations of Tilt() and Sketch() with no luck.) Is there a way to generate a tilt file from scratch in the Python sdk, the way @Prystopia does with C#?

**Comment by Prystopia** [comment]
Hi everyone, I've finally gotten around to writing an overview of the project which can be found [here](https://www.prystopia.com/blog/using-vr-in-evo-art).

**Pull request closed without merging**
