### PR TITLE
add reveal strokes example

### PR DESCRIPTION
**Pull request by n1ckfg**
Reveal strokes script and example scene--a simple Unity task, but a common artist request.

### CODE REVIEW

**Comment by dubois** [comment]
Hi Nick, thanks for your pull request. I'm declining this one since Tilt Brush Toolkit needs to remain focused on bringing Tilt Brush exports into Unity. Tutorials for the artist community are important for sure, but we're not ready to write, maintain, and field questions about Unity. We're also thinking of removing the Examples folder for the same reason.

**Comment by andybak** [comment]
> We're also thinking of removing the Examples folder for the same reason.

Wouldn't it therefore make sense to create a separate repo that contains Examples (and to which this PR could be reapplied?)

**Comment by n1ckfg** [comment]
Sounds good to me--those Sequence examples I think would be a little tricky for a beginner to recreate, but they're nice and easy to modify

**Comment by dubois** [comment]
Yes, but we still don't have the bandwidth to field questions about,
maintain, and augment a repo of general Unity tutorials. An interested
community member could of course do so.

**Comment by HelloOrwell** [comment]
Speaking as a complete amateur and someone that began their interest in Unity through tilt brush, I can tell you that every little bit helps. Most of us aren't even aware of what's possible. So although I understand not having the resources, I can tell you from experience we are wandering aimlessly just reaching for something. There's little to no help in these matters. But onwards we go.

**Comment by HelloOrwell** [comment]
@n1ckfg downloaded and sending you wishes for infinite spins around the sun. Things like this are a godsend for newbies like me.

**Comment by dubois** [comment]
Looping back around to this, we would love to get to a place where people interested in VR art can congregate, discuss, and ask each other questions. There's clearly a need for both highly-specific expert-level information (eg, how to effectively manipulate a USD export to create something like A Show of Kindness) as well as novice-friendly "how to even get started" info.

Our [product forums](https://productforums.google.com/forum/#!forum/tilt-brush) could be that place.

**Pull request closed without merging**
