### PR TITLE
Transform Python code to a PyPi package.

### LINKED ISSUE #6: Create PyPi package for the Python code
I suggest to move `bin` and `tests` under `Python` directory and create `setup.py` to turn the Python part of the toolkit to a PyPi package.

Even if we don't want to publish the package right now it would be useful to install it locally.

Here is the [draft commit](https://github.com/Sitin/tilt-brush-toolkit/commit/5a0ec37653a2bdab29efb19792fa4120c23b55ad).

### PR DESCRIPTION
**Pull request by Sitin**
This one is intended to resolve #6.

Before merging this PR we may decide the following:

- [ ] Verify package name, description and add the author (probably Google Inc.).
- [ ] Choose CLI tools from `Python/bin` which should be registered as executables. Currently, I've registered nothing since some of them serve just as examples.

### CODE REVIEW

**Comment by dubois** [comment]
We have no current plans to publish to PyPI.

We might accept a very simple PR that allows end-users to run "setup.py install" as a maybe-more-convenient way to get the code into sys.path. But the expected use case is for artist/makers to update by pulling straight from git and modifying sys.path or PYTHONPATH

**Comment by Sitin** [comment]
So, we can merge this one.

Since I believe that

```sh
pip install -e Python/
```

is a better and more obvious and concise way to install the tool.

**Comment by andybak** [comment]
>  But the expected use case is for artist/makers to update by pulling straight from git and modifying sys.path or PYTHONPATH

That's a very strange way to use Python package. Even the most basic Python tutorials recommend virtualenv and pip.

**Comment by Sitin** [comment]
This is a native pip solution and it works for virtualenvs as well.
`Python/` here is the location for the Python part of the toolkit relative to the repository root.

**Comment by dubois** [comment]
Hi, thanks for your input. I don't want to accept dependencies on anything which doesn't come with Python. So, no setuptools in the code (distutils is ok). The docs should not rely on pip (mentioning it as an alternate approach is ok).

Rationale: not all people using this are going to be Python users, or even be interested in doing things the Python way, let alone be interested in the vagaries of the Python packaging ecosystem. Additional process complexity is undesirable.

bin/ directory should not be moved; it uses the python modules, but should not be part of the module.

I feel like this is a minor improvement at best; unless you feel really strongly about it let's do at most one more back and forth before resolving one way or another.

**Comment by andybak** [comment]
You make a good point. But doesn't pip come built in with Python now? It's so long since I've started from a clean machine I don't know - but I thought "standard practice" and "base install" had converged.

**Comment by dubois** [comment]
Yeah, pip still requires the use of finding + downloading "get_pip.py". Might be standard with python 3, but all our development is still 2.7.x.

**Pull request closed without merging**
